[package]
name = "kproxy-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kproxy-core = {path = "../kproxy-core"}
tokio = { version = "1.36.0", features = ["full"] }
log = "0.4"